#!/usr/bin/env bash

source "${SNAP}/init"
logger "Running post-refresh ${SNAP_NAME} (uuid: ${UUID})"

logger "Running config test"
set -e
$SNAP/bin/hass --script check_config --config "${SNAP_DATA}"
