#!/usr/bin/env bash

source "${SNAP}/init"
logger "Running post-refresh ${SNAP_NAME} (uuid: ${UUID})"

logger "Running config test"
set -e
CC="${SNAP_DATA}/custom_components"
CCT="${SNAP_DATA}/.custom_components"

if [ -d "${CCT}" ]; then
    if [ ! -d "${CC}" ]; then
        mv "${CCT}" "${CC}"
    fi
fi
#
# if [ -d "${CC}" ]; then
#     logger "Disabling custom components"
#     mv "${CC}" "${CCT}"
# fi
#
$SNAP/bin/hass --script check_config --config "${SNAP_DATA}"
#
# if [ -d "${CC}" ]; then
#     logger "Enabling custom components"
#     mv "${CCT}" "${CC}"
# fi
#
# exit $RES
